checkpoint:
  dir: checkpoints/${exp.name}/${dataset.name}/${method.name}_${model}
  test_iter: best_model
  time: latest
defaults:
- dataset: tabula_muris
- method: maml
exp:
  name: baseline_iter30_lr0p001
  resume: false
  save_freq: 10
  seed: 42
  val_freq: 1
iter_num: 10
lr: 0.001
mode: train
model: FCNet
n_query: ???
n_shot: ???
n_way: ???
optimizer: Adam
optimizer_cls:
  _target_: torch.optim.${optimizer}
  lr: ${lr}
wandb:
  entity: tim-wiebelhaus
  mode: offline
  project: dl-team-18
